//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crabwise.PDFtoEPUB.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Crabwise.PDFtoEPUB.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;container version=&quot;1.0&quot; xmlns=&quot;urn:oasis:names:tc:opendocument:xmlns:container&quot;&gt;
        ///  &lt;rootfiles&gt;
        ///    &lt;rootfile full-path=&quot;OEBPS/content.opf&quot; media-type=&quot;application/oebps-package+xml&quot;/&gt;
        ///  &lt;/rootfiles&gt;
        ///&lt;/container&gt;.
        /// </summary>
        internal static string container {
            get {
                return ResourceManager.GetString("container", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ade:template xmlns=&quot;http://www.w3.org/1999/xhtml&quot; xmlns:ade=&quot;http://ns.adobe.com/2006/ade&quot;
        ///		 xmlns:fo=&quot;http://www.w3.org/1999/XSL/Format&quot;&gt;
        ///
        ///  &lt;fo:layout-master-set&gt;
        ///   &lt;fo:simple-page-master master-name=&quot;single_column&quot;&gt;
        ///		&lt;fo:region-body margin-bottom=&quot;3pt&quot; margin-top=&quot;0.5em&quot; margin-left=&quot;3pt&quot; margin-right=&quot;3pt&quot;/&gt;
        ///    &lt;/fo:simple-page-master&gt;
        ///  
        ///    &lt;fo:simple-page-master master-name=&quot;single_column_head&quot;&gt;
        ///		&lt;fo:region-before extent=&quot;8.3em&quot;/&gt;
        ///		&lt;fo:region-body margin-bottom=&quot;3pt&quot; margin-top=&quot;6em&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string page_template {
            get {
                return ResourceManager.GetString("page_template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /* Style Sheet */
        ////* This defines styles and classes used in the book */
        ///body { margin-left: 5%; margin-right: 5%; margin-top: 5%; margin-bottom: 5%; text-align: justify; }
        ///pre { font-size: x-small; }
        ///h1 { text-align: center; }
        ///h2 { text-align: center; }
        ///h3 { text-align: center; }
        ///h4 { text-align: center; }
        ///h5 { text-align: center; }
        ///h6 { text-align: center; }
        ///h7 { text-align: center; color: silver; }
        ///.CI {
        ///    text-align:center;
        ///    margin-top:0px;
        ///    margin-bottom:0px;
        ///    padding:0px;
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string stylesheet {
            get {
                return ResourceManager.GetString("stylesheet", resourceCulture);
            }
        }
    }
}
